name: Trigger OpenShift Build

on:
  push:
   branches:
     - main
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger OpenShift Build
        run: |
               curl -k -X POST \
                 -H "Authorization: Bearer ${{ secrets.OPENSHIFT_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d '{
                   "kind": "BuildRequest",
                   "apiVersion": "build.openshift.io/v1",
                   "metadata": {
                     "name": "sample-for-openshift-cicd"
                     }
               }' \
               "${{ vars.K8SCLUSTERURL }}"