name: Trigger OpenShift Build

on:
  push:
   branches:
     - master
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger OpenShift Build
        run: |
               curl -k -X POST \
                 -H "Authorization: Bearer ${{ secrets.OPENSHIFT_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d '{
                   "kind": "BuildRequest",
                   "apiVersion": "build.openshift.io/v1",
                   "metadata": {
                     "name": "sample-for-openshift-cicd"
                     }
               }' \
              "https://api.rm1.0a51.p1.openshiftapps.com:6443/apis/build.openshift.io/v1/namespaces/zahir-can-dev/buildconfigs/sample-for-openshift-cicd/instantiate"